apiVersion: v1
kind: Namespace
metadata:
  name: infrasentry-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: infrasentry-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: hashicorp/http-echo:1.0
          args: ["-text=InfraSentry healthy"]
          ports:
            - containerPort: 5678
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 1
            periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: infrasentry-lab
spec:
  selector:
    app: echo
  ports:
    - name: http
      port: 80
      targetPort: 5678
